name: Bug Report
description: Reportar um problema ou comportamento inesperado
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Obrigado por reportar este bug! Preencha as informações abaixo para nos ajudar a resolver o problema.

  - type: input
    id: version
    attributes:
      label: Versão da API
      description: Qual versão do Zé da API você está usando?
      placeholder: "ex: 3.10.0"
    validations:
      required: true

  - type: dropdown
    id: plan
    attributes:
      label: Plano de Assinatura
      options:
        - Starter
        - Pro
        - Enterprise
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Descrição do Bug
      description: Descreva o problema de forma clara e objetiva.
      placeholder: O que aconteceu?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Passos para Reproduzir
      description: Liste os passos necessários para reproduzir o problema.
      placeholder: |
        1. Enviar request POST para /send-text
        2. Com o payload: { "phone": "5511999999999", "message": "teste" }
        3. Receber erro 500
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Comportamento Esperado
      description: O que deveria ter acontecido?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Comportamento Atual
      description: O que aconteceu de fato? Inclua mensagens de erro, códigos HTTP, etc.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto Adicional
      description: Logs, screenshots, configuração do ambiente, etc.
