name: Dúvida
description: Tirar uma dúvida sobre a API ou integração
title: "[Dúvida]: "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Tem alguma dúvida? Estamos aqui para ajudar!

  - type: textarea
    id: question
    attributes:
      label: Sua Dúvida
      description: Descreva sua dúvida da forma mais clara possível.
      placeholder: Como faço para...
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Contexto
      description: O que você já tentou? Qual documentação consultou?
      placeholder: |
        Já li a documentação em...
        Tentei fazer...

  - type: dropdown
    id: plan
    attributes:
      label: Plano de Assinatura
      options:
        - Starter
        - Pro
        - Enterprise
        - Ainda não sou assinante
    validations:
      required: true

  - type: dropdown
    id: topic
    attributes:
      label: Área da dúvida
      options:
        - Envio de mensagens
        - Webhooks / Eventos
        - Instâncias / Conexão
        - Mídia (imagens, documentos, áudio)
        - Grupos / Comunidades
        - Autenticação / Token
        - Postman / OpenAPI
        - Outro
    validations:
      required: true
